export class Account {
    email!: String;
    password!: String;
    name!: String;
    phone!: String;
    userId!: String;
    state!:String;
    fullName!: String;
    nickName!: String;
    country!: String;
    Address_one!: String;
    Address_two!: String;
    city!: String;
    pin!: String;
    
}

// Generated by https://quicktype.io

export interface Login {
    error:                boolean;
    message:              string;
    role:                 string;
    userId:               string;
    profileImage:         string;
    _is_email_verified_:  boolean;
    _is_mobile_verified_: boolean;
    token:                string;
}
